// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/06/2026, 23:59:11
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/signo/Documents/Codex/2026-06-28/use-o-figma-para-revisar-o/outputs/portfolio-nuxt-tailwind/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Documents/Codex/2026-06-28/use-o-figma-para-revisar-o/outputs/portfolio-nuxt-tailwind/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Documents/Codex/2026-06-28/use-o-figma-para-revisar-o/outputs/portfolio-nuxt-tailwind/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Documents/Codex/2026-06-28/use-o-figma-para-revisar-o/outputs/portfolio-nuxt-tailwind/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Documents/Codex/2026-06-28/use-o-figma-para-revisar-o/outputs/portfolio-nuxt-tailwind/plugins/**/*.{js,ts,mjs}","C:/Users/signo/Documents/Codex/2026-06-28/use-o-figma-para-revisar-o/outputs/portfolio-nuxt-tailwind/composables/**/*.{js,ts,mjs}","C:/Users/signo/Documents/Codex/2026-06-28/use-o-figma-para-revisar-o/outputs/portfolio-nuxt-tailwind/utils/**/*.{js,ts,mjs}","C:/Users/signo/Documents/Codex/2026-06-28/use-o-figma-para-revisar-o/outputs/portfolio-nuxt-tailwind/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Documents/Codex/2026-06-28/use-o-figma-para-revisar-o/outputs/portfolio-nuxt-tailwind/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Documents/Codex/2026-06-28/use-o-figma-para-revisar-o/outputs/portfolio-nuxt-tailwind/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Documents/Codex/2026-06-28/use-o-figma-para-revisar-o/outputs/portfolio-nuxt-tailwind/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;