// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 30/06/2026, 23:59:37
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/signo/Downloads/fernanda-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Downloads/fernanda-portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Downloads/fernanda-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Downloads/fernanda-portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Downloads/fernanda-portfolio/plugins/**/*.{js,ts,mjs}","C:/Users/signo/Downloads/fernanda-portfolio/composables/**/*.{js,ts,mjs}","C:/Users/signo/Downloads/fernanda-portfolio/utils/**/*.{js,ts,mjs}","C:/Users/signo/Downloads/fernanda-portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Downloads/fernanda-portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Downloads/fernanda-portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/signo/Downloads/fernanda-portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;